services:
    monogramm_proxmox.api:
        class: ProxmoxVE\Proxmox
        arguments: 
            $credentials:
                hostname: "%monogramm_proxmox.hostname%"
                username: "%monogramm_proxmox.username%"
                password: "%monogramm_proxmox.password%"
                realm: "%monogramm_proxmox.realm%"
                port: "%monogramm_proxmox.port%"

    proxmox:
        alias: monogramm_proxmox.api
